name: CI-CD

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          yarn install
          yarn run build
        env:
          GRIDSOME_API_KEY_EMAIL: ${{ secrets.API_KEY_EMAIL }}
          GRIDSOME_API_KEY_RECAPTCHA_FRONT: ${{ secrets.API_KEY_RECAPTCHA_FRONT }}
          GRIDSOME_API_KEY_RECAPTCHA_BACK: ${{ secrets.API_KEY_RECAPTCHA_BACK }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
