name: CI-CD

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          yarn install
          yarn run build
        env:
          GRIDSOME_API_URL: ${{ secrets.GRIDSOME_API_URL }}
          GRIDSOME_SERVER_API_KEY: ${{ secrets.GRIDSOME_SERVER_API_KEY }}
          GRIDSOME_RECAPTCHA_API_KEY: ${{ secrets.GRIDSOME_RECAPTCHA_API_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
